"""Initial migration

Revision ID: 9f236671dab7
Revises: 
Create Date: 2025-09-19 14:41:25.619799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f236671dab7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(length=255), nullable=False, comment='许可证密钥'),
    sa.Column('organization_name', sa.String(length=200), nullable=False, comment='购买机构名称'),
    sa.Column('contact_person', sa.String(length=100), nullable=False, comment='联系人'),
    sa.Column('contact_email', sa.String(length=100), nullable=False, comment='联系邮箱'),
    sa.Column('contact_phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True, comment='设备指纹'),
    sa.Column('annual_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='年费'),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False, comment='购买日期'),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False, comment='到期日期'),
    sa.Column('is_active', sa.Integer(), nullable=True, comment='是否激活'),
    sa.Column('activation_date', sa.DateTime(timezone=True), nullable=True, comment='激活日期'),
    sa.Column('last_validation', sa.DateTime(timezone=True), nullable=True, comment='最后验证时间'),
    sa.Column('validation_count', sa.Integer(), nullable=True, comment='验证次数'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_key')
    )
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('real_name', sa.String(length=50), nullable=False, comment='真实姓名'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别'),
    sa.Column('age', sa.Integer(), nullable=True, comment='年龄'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CAMPUS_ADMIN', 'COACH', 'STUDENT', name='userrole'), nullable=False, comment='用户角色'),
    sa.Column('campus_id', sa.Integer(), nullable=True, comment='所属校区ID'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('id_number', sa.String(length=18), nullable=True, comment='身份证号'),
    sa.Column('is_active', sa.Integer(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('campuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='校区名称'),
    sa.Column('address', sa.Text(), nullable=False, comment='校区地址'),
    sa.Column('contact_person', sa.String(length=50), nullable=False, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('contact_email', sa.String(length=100), nullable=True, comment='联系邮箱'),
    sa.Column('admin_id', sa.Integer(), nullable=True, comment='校区管理员ID'),
    sa.Column('is_main_campus', sa.Integer(), nullable=True, comment='是否为中心校区'),
    sa.Column('is_active', sa.Integer(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campuses_id'), 'campuses', ['id'], unique=False)
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('level', sa.Enum('SENIOR', 'INTERMEDIATE', 'JUNIOR', name='coachlevel'), nullable=False, comment='教练级别'),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False, comment='每小时收费'),
    sa.Column('achievements', sa.Text(), nullable=True, comment='比赛成绩描述'),
    sa.Column('max_students', sa.Integer(), nullable=True, comment='最多指导学员数'),
    sa.Column('current_students', sa.Integer(), nullable=True, comment='当前指导学员数'),
    sa.Column('approval_status', sa.String(length=20), nullable=True, comment='审核状态'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='审核人ID'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='审核时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_coaches_id'), 'coaches', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='金额'),
    sa.Column('payment_method', sa.String(length=20), nullable=False, comment='支付方式'),
    sa.Column('payment_status', sa.String(length=20), nullable=True, comment='支付状态'),
    sa.Column('transaction_id', sa.String(length=100), nullable=True, comment='交易ID'),
    sa.Column('payment_type', sa.String(length=20), nullable=False, comment='支付类型: recharge/course/competition/license'),
    sa.Column('related_id', sa.Integer(), nullable=True, comment='关联ID(课程ID/比赛ID等)'),
    sa.Column('qr_code_url', sa.String(length=255), nullable=True, comment='支付二维码URL'),
    sa.Column('payment_time', sa.DateTime(timezone=True), nullable=True, comment='支付时间'),
    sa.Column('refund_time', sa.DateTime(timezone=True), nullable=True, comment='退款时间'),
    sa.Column('refund_reason', sa.Text(), nullable=True, comment='退款原因'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID(线下支付时)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('account_balance', sa.Numeric(precision=10, scale=2), nullable=True, comment='账户余额'),
    sa.Column('max_coaches', sa.Integer(), nullable=True, comment='最多选择教练数'),
    sa.Column('current_coaches', sa.Integer(), nullable=True, comment='当前教练数'),
    sa.Column('monthly_cancellations', sa.Integer(), nullable=True, comment='本月取消预约次数'),
    sa.Column('last_cancellation_reset', sa.DateTime(timezone=True), nullable=True, comment='上次重置取消次数时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='目标类型(user/booking/payment等)'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='目标ID'),
    sa.Column('description', sa.Text(), nullable=False, comment='操作描述'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理'),
    sa.Column('extra_data', sa.Text(), nullable=True, comment='额外数据(JSON格式)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False, comment='教练ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学员ID'),
    sa.Column('campus_id', sa.Integer(), nullable=False, comment='校区ID'),
    sa.Column('table_number', sa.String(length=10), nullable=True, comment='球台编号'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='结束时间'),
    sa.Column('duration_hours', sa.Numeric(precision=3, scale=1), nullable=False, comment='预约时长(小时)'),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False, comment='每小时费用'),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='总费用'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='预约状态'),
    sa.Column('booking_message', sa.Text(), nullable=True, comment='预约留言'),
    sa.Column('response_message', sa.Text(), nullable=True, comment='回复留言'),
    sa.Column('cancelled_by', sa.Integer(), nullable=True, comment='取消发起人ID'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='取消时间'),
    sa.Column('cancellation_reason', sa.Text(), nullable=True, comment='取消原因'),
    sa.Column('cancel_confirmed_by', sa.Integer(), nullable=True, comment='取消确认人ID'),
    sa.Column('cancel_confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='取消确认时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.ForeignKeyConstraint(['cancel_confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('coach_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False, comment='教练ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学员ID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='申请状态: pending/approved/rejected'),
    sa.Column('applied_by', sa.String(length=20), nullable=False, comment='申请发起方: student/admin'),
    sa.Column('application_message', sa.Text(), nullable=True, comment='申请留言'),
    sa.Column('response_message', sa.Text(), nullable=True, comment='回复留言'),
    sa.Column('responded_by', sa.Integer(), nullable=True, comment='回复人ID'),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True, comment='回复时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_students_id'), 'coach_students', ['id'], unique=False)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='比赛名称'),
    sa.Column('campus_id', sa.Integer(), nullable=False, comment='举办校区ID'),
    sa.Column('competition_date', sa.DateTime(timezone=True), nullable=False, comment='比赛日期'),
    sa.Column('registration_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='报名费'),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=False, comment='报名截止时间'),
    sa.Column('max_participants_per_group', sa.Integer(), nullable=True, comment='每组最大参赛人数'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='比赛状态'),
    sa.Column('description', sa.Text(), nullable=True, comment='比赛描述'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_id'), 'competitions', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False, comment='教练ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学员ID'),
    sa.Column('campus_id', sa.Integer(), nullable=False, comment='校区ID'),
    sa.Column('table_number', sa.String(length=10), nullable=False, comment='球台编号'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='结束时间'),
    sa.Column('duration_hours', sa.Numeric(precision=3, scale=1), nullable=False, comment='课程时长(小时)'),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False, comment='每小时费用'),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='总费用'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='课程状态'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('competition_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False, comment='比赛ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学员ID'),
    sa.Column('group_type', sa.String(length=20), nullable=False, comment='报名组别'),
    sa.Column('player_number', sa.Integer(), nullable=True, comment='参赛编号'),
    sa.Column('table_assignments', sa.Text(), nullable=True, comment='球台分配(JSON格式)'),
    sa.Column('match_schedule', sa.Text(), nullable=True, comment='比赛赛程(JSON格式)'),
    sa.Column('payment_id', sa.Integer(), nullable=True, comment='支付记录ID'),
    sa.Column('registration_status', sa.String(length=20), nullable=True, comment='报名状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_registrations_id'), 'competition_registrations', ['id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='课程ID'),
    sa.Column('evaluator_id', sa.Integer(), nullable=False, comment='评价人ID'),
    sa.Column('evaluator_type', sa.String(length=20), nullable=False, comment='评价人类型: student/coach'),
    sa.Column('content', sa.Text(), nullable=False, comment='评价内容'),
    sa.Column('rating', sa.Integer(), nullable=True, comment='评分(1-5)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_competition_registrations_id'), table_name='competition_registrations')
    op.drop_table('competition_registrations')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_competitions_id'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_coach_students_id'), table_name='coach_students')
    op.drop_table('coach_students')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_coaches_id'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_index(op.f('ix_campuses_id'), table_name='campuses')
    op.drop_table('campuses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_table('licenses')
    # ### end Alembic commands ###
